### ISSUE TITLE
Connect() to 10.21.21.11:9050 failed after select(): Connection refused (111)

### ISSUE THREAD

**Issue by bhaskarndas** [getumbrel/umbrel#425]
Hi After installation was completed and after sometime I rebooted via http://umbrel.local/settings
After that the screen is stuck at Loading LND.

Upon checking the logs

This is the message I am getting:

Connect() to 10.21.21.11:9050 failed after select(): Connection refused (111)

Please provide solution for this.

**Comment by gielemans** [comment]
My Linux install (Ubuntu 21) freezes after synchronizing 75% of the blockchain. The syslog shows an error “failed to connect daemon at 10.21.21.8:8332: No route to host (os error 113)”. Isn’t this odd since 10.21.21.0/24 is a private range? Any thoughts on this?

**Comment by louneskmt** [comment]
Umbrel uses an internal Docker network. These IPs correspond to containers IP addresses. 

For @bhaskarndas: LND cannot connect to the Tor container. A reboot / restart should solve this.  

For @gielemans: It looks like a container (I suppose LND?) cannot connect to the Bitcoin container (port 8332 -> Bitcoin Core's RPC server). Have you tried a simple reboot yet? If yes, can you send logs from Bitcoin Core ? 

```
docker-compose logs bitcoin
```

**Comment by bhaskarndas** [comment]
System and container both have been rebooted several times. This issue cropped up after I gave restart from settings on the dashboard. After that It has not solved. Ultimately I had to remove umbrel.

**Comment by gielemans** [comment]
Oh!!! What a blunder I made... Disk space was not sufficient. Issue solved!

**Comment by Prideone** [comment]
Greetings people !!!

Perform the steps to start Umbrel (along with the "docker"). Everything started perfectly, and when the blocks were updated I could access Umbrel with the IP of "http://192.168.100.30/".

The problem is that when it reaches 100% it stops working for me, I cannot access Umbrel from the IP from before. (never starts).
In the "docker" application I see the 10 docker containers, but one never starts (which before if), I mean "lncm / bitcoind: v0.21.0", I mean, "Bitcoind".

The docker reports "restarting" over and over and never starts (which it used to do without problems.

Restart the computer and there is no case, I restart Docker and neither.

With this command "docker-compose logs bitcoin" it tells me the following error:
localhost: /home/prideone-suse-15.2/.bitcoin # docker-compose logs bitcoin
Attaching to bitcoin
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
bitcoin | Error: Failed loading settings file:
bitcoin | - Unable to parse settings file /data/.bitcoin/settings.json
localhost: /home/prideone-suse-15.2/.bitcoin #


Does anyone know what the error is? Thanks!!!!! 

PS: I don't know how to write in English, and I used google translate.

**Comment by AaronDewes** [comment]
Try running `rm ~/umbrel/bitcoin/settings.json` over SSH (Instructions on UmbrelInfo.gitlab.io)

**Comment by Prideone** [comment]
Hello!!

I still can't access the IP (which when I started it for the first time two days ago and started downloading the Blockchain if the IP and the applications within Umbrel worked. The problem was that when it reached 100% it stopped working).

I did the command "./scripts/debug --upload" and it gave the following:
`Hello!!

I still can't access the IP (which when I started it for the first time two days ago and started downloading the Blockchain if the IP and the applications within Umbrel worked. The problem was that when it reached 100% it stopped working).

I did the command "./scripts/debug --upload" and it gave the following:



The error is that the folder "/ usr / local / bin /" is empty.
I have installed the library "libsqlite3.so.0". `


The error is that the folder "/ usr / local / bin /" is empty.
I have installed the library "libsqlite3.so.0". 

I already uploaded the error (https://umbrel-paste.vercel.app/1210a31). I started an Umbrel telegram chat which is a bot "pablo_weather_bot", I uploaded the link of my error but he did not answer me yet. I put "/ start" and it didn't respond either.

I don't understand much about "SSH", but in the terminal it gives me an error:
```
localhost: /home/prideone-suse-15.2/.bitcoin # ssh umbrel@umbrel.local
ssh: Could not resolve hostname umbrel.local: Name or service not known
localhost: /home/prideone-suse-15.2/.bitcoin # shh umbrel@192.168.100.30
If 'shh' is not a typo, you can use the order not found search, to find out which package it belongs to, like this:
     cnf shh
localhost: /home/prideone-suse-15.2/.bitcoin #
```

Thanks for helping guys !!! I hope to give you more useful information now.

**Comment by louneskmt** [comment]
Have you already funds on your Umbrel? If not, consider just installing Umbrel again from scratch, it will be less of an headache.

**Comment by Prideone** [comment]
It's the second time I've done it, and I was never able to get back into Umbrel after 100% blockchain sync.

I have no problems starting back (it's just 2 days of resynchronization). I'm going to look at that particular folder "/ usr / local / bin /" to see if it is empty or full during synchronization with the blockchain.

Thanks!!!! Then I tell you how everything was ^. ^

**Comment by Prideone** [comment]
Hello people!!!

He deleted all the Umbrel info again. Delete the docker and thoroughly clean the images, volumes and containers (before cleaning had not done so cleanly).

Now I am going to put the commands that I had done before in case you see something between the before and now.

------ 1) The file "/root/Umbrel/bitcoin/settings.json" is empty too now (as in my second attempt when it failed). Here I send you the file:

localhost: ~ / Umbrel / bitcoin # cat settings.json
{
    }

(I forgot to tell you that I had previously removed it to the archive but did nothing to fix the problem). 

------ 2) I do these commands from the "ssh":

```
localhost: ~ / Umbrel # ssh umbrel@umbrel.local
ssh: Could not resolve hostname umbrel.local: Name or service not known
localhost: ~ / Umbrel # ssh umbrel@192.168.100.30
ssh: connect to host 192.168.100.30 port 22: Connection refused 
```

------ 3) Now I look at debugging with the command "./scripts/debug –upload". Sale todo bien, hasta el apartado de bitcoin: 

```
=====================
= Umbrel debug info =
=====================

Umbrel version
--------------
0.3.7

Filesystem information
----------------------
S.ficheros     Tamaño Usados  Disp Uso% Montado en
devtmpfs         7,8G      0  7,8G   0% /dev
tmpfs            7,8G    73M  7,8G   1% /dev/shm
tmpfs            7,8G    19M  7,8G   1% /run
tmpfs            7,8G      0  7,8G   0% /sys/fs/cgroup
/dev/sda1         30G    17G   12G  58% /
/dev/loop0        99M    99M     0 100% /snap/core/10823
/dev/loop1        56M    56M     0 100% /snap/core18/1944
/dev/loop2        65M    65M     0 100% /snap/gtk-common-themes/1513
/dev/loop3        98M    98M     0 100% /snap/core/10583
/dev/loop4        56M    56M     0 100% /snap/core18/1988
/dev/loop5       103M   103M     0 100% /snap/bitcoin-core/87
/dev/loop6       162M   162M     0 100% /snap/brave/99
/dev/loop7       162M   162M     0 100% /snap/brave/98
/dev/loop8        65M    65M     0 100% /snap/gtk-common-themes/1514
/dev/sda3         59G    45G   11G  82% /home
/dev/sdb1        393G   326G   48G  88% /mnt/sdb1
/dev/sdb2        523G   279M  496G   1% /root/Umbrel
/dev/sdc1        102G    60M   96G   1% /root/Umbrel/electrs
tmpfs            1,6G    20K  1,6G   1% /run/user/1000
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/96bc5c34bbc3d100ef67e2bd4aef322c31c709111b9d146fe53d538384c01581/merged
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/bc15d1fa3f3310d2ad1416a5fb6043c66dc2b22b78c0bede0d4e825b64af8795/merged
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/56b722d365caea72cdcbfd91e412159223faa52cf334fd3b6fce5b9dfcd27009/merged
shm               64M      0   64M   0% /var/lib/docker/containers/1f1cb407b018418de2915ea95cc4db3fa2b3a0ce6727aa5472a0e943437972b2/mounts/shm
shm               64M      0   64M   0% /var/lib/docker/containers/2cf3e9a7e64d589e0c52397f6bdf28da40b82c3ac307732553090555e755e986/mounts/shm
shm               64M      0   64M   0% /var/lib/docker/containers/972b6dc33514dfe08281b407641b214ec8a684cab28bd8ebcfe219d0ef0674a6/mounts/shm
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/1270706ec6e53bf7b84d049b06ab19a7ed30ff6fc7c28d9512a78bb65a23a746/merged
shm               64M      0   64M   0% /var/lib/docker/containers/179f97b19399727c3ebd521937a50608422dc33cdde8ea68b178659b24f85798/mounts/shm
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/23eb6d2ed70d8e06434fd576483990b2937efa48c5fb86ceda5e86462afd4b32/merged
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/114d53dfbbb6072208257e0ad486884d2057b523d7825dd4087e890c5a60f958/merged
shm               64M      0   64M   0% /var/lib/docker/containers/980dcd99c66107ec5f87ca816a37fd33aec6797bfd3ff73d16d2506cb704bb3c/mounts/shm
shm               64M      0   64M   0% /var/lib/docker/containers/7b8f74226cd9fe6942ad12d269336c43bff5b19ccf5b689601311caf1fc18d65/mounts/shm
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/163f683a9c2e251c46a873f7dea48bae0cdc121efe574e91e55846feb3590bcf/merged
shm               64M      0   64M   0% /var/lib/docker/containers/1989873c2a4817802aaa9e61d97b4642d7fee07fee1bce435b96c36fdb670e90/mounts/shm
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/3ee8acf058905af81117509d3105174071b5ed87a1e25e491dbbe963731b5042/merged
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/50fa02c7db230f084fedfcc348f77af650c1a0a67266689918d1d3dfd00ecbf6/merged
overlay           30G    17G   12G  58% /var/lib/docker/overlay2/f2373fd0ff29fd382eb503ab747525c68e02ff9ef5c3e9eb9fe37bb9686451fc/merged
shm               64M      0   64M   0% /var/lib/docker/containers/c51c741cd28238cfd3781bce9cee1ec7f5ad167027cc5f450609df004b01657a/mounts/shm
shm               64M      0   64M   0% /var/lib/docker/containers/2dbcb3766aeeafc2e02905f6e0f9f0f4975e4fb346c1e9546c18c66a37936eba/mounts/shm
shm               64M      0   64M   0% /var/lib/docker/containers/b30cb9c309293dacce383131666078b06b8bf13793cbbf6cd1a61009c83fd924/mounts/shm

Filename                                Type            Size    Used    Priority

Karen logs
----------

karen is running in /root/Umbrel/events
Got signal: change-password
karen is getting triggered!
This script must only be run on Umbrel OS
Got signal: shutdown
karen is getting triggered!
Stopping installed apps...


Stopping Docker services...

Stopping neutrino-switcher ... done
Stopping middleware        ... done
Stopping electrs           ... done
Stopping bitcoin           ... done
Stopping lnd               ... done
Stopping nginx             ... done
Stopping manager           ... done
Stopping frontail          ... done
Stopping dashboard         ... done
Stopping tor               ... done
Removing neutrino-switcher ... done
Removing middleware        ... done
Removing electrs           ... done
Removing bitcoin           ... done
Removing lnd               ... done
Removing nginx             ... done
Removing manager           ... done
Removing frontail          ... done
Removing dashboard         ... done
Removing tor               ... done
Removing network umbrel_main_network
karen is running in /root/Umbrel/events

Docker containers
-----------------
NAMES               STATUS
middleware          Up 2 minutes
electrs             Up 2 minutes
neutrino-switcher   Up 2 minutes
bitcoin             Up 2 minutes
lnd                 Up 2 minutes
nginx               Up 2 minutes
manager             Up 2 minutes
frontail            Up 2 minutes
dashboard           Up 2 minutes
tor                 Up 2 minutes

Bitcoin Core logs
-----------------

Attaching to bitcoin
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000042e80cadd06bbaa3be80dcd2083af2ee4dfaaa4f966370c2b1dea1 height=82312 version=0x00000001 log2_work=54.789900 tx=120887 date='2010-09-27T07:15:12Z' progress=0.000195 cache=2.0MiB(13412txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000000858791fc265eae78a207f1c19066b407395929ce8dac0aa0b9ac1 height=82313 version=0x00000001 log2_work=54.790082 tx=120891 date='2010-09-27T07:21:58Z' progress=0.000195 cache=2.0MiB(13416txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000043c3365934d75aa6d5d2caecf41675fc89e6dbdf8e63ad62bd715a height=82314 version=0x00000001 log2_work=54.790265 tx=120892 date='2010-09-27T07:24:27Z' progress=0.000195 cache=2.0MiB(13417txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000001ad11f0a485fdb539a42d6abcb906fbd43de67c8a9d93a52297df0 height=82315 version=0x00000001 log2_work=54.790448 tx=120894 date='2010-09-27T07:30:09Z' progress=0.000195 cache=2.0MiB(13418txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000002585f9a26f23eb1716306f3d0c4101e6625b417038f68c4184bfc6 height=82316 version=0x00000001 log2_work=54.790630 tx=120896 date='2010-09-27T07:32:41Z' progress=0.000195 cache=2.0MiB(13420txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000001a3f5a8956bbcaa00c9c73dde4ac310cd2de879bbf9e8cd57cfc0 height=82317 version=0x00000001 log2_work=54.790813 tx=120898 date='2010-09-27T07:35:39Z' progress=0.000195 cache=2.0MiB(13422txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000031e19afec8ea0b35b298ab0f197768c8c078c5f822e40b92838ad1 height=82318 version=0x00000001 log2_work=54.790995 tx=120903 date='2010-09-27T07:47:56Z' progress=0.000195 cache=2.0MiB(13425txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000221eab80658dc4fd85066a4d5970b5f4fd94e07ac4df33397a3249 height=82319 version=0x00000001 log2_work=54.791177 tx=120907 date='2010-09-27T08:04:49Z' progress=0.000195 cache=2.0MiB(13429txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000002fab39af75f786f620364b0428c44500ecdbf979e8814b31f4bc2d height=82320 version=0x00000001 log2_work=54.791360 tx=120910 date='2010-09-27T08:15:09Z' progress=0.000195 cache=2.0MiB(13410txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000026984417bd8477c6adef25ab25b8dd14b0a5e4f5a826b916517474 height=82321 version=0x00000001 log2_work=54.791542 tx=120911 date='2010-09-27T08:16:07Z' progress=0.000195 cache=2.0MiB(13411txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000002a3799f74bc061004d3bf90b51df3242207cecaa9ca9c15395ea8 height=82322 version=0x00000001 log2_work=54.791725 tx=120912 date='2010-09-27T08:18:55Z' progress=0.000195 cache=2.0MiB(13412txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000016ef2f56e4104d588be687faae6c30b1e2135dda40de37e58f2955 height=82323 version=0x00000001 log2_work=54.791907 tx=120913 date='2010-09-27T08:22:08Z' progress=0.000195 cache=2.0MiB(13413txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000000befd946b276f6ce40b73d98913eb0aca2a14d59c00ba2ef53a72 height=82324 version=0x00000001 log2_work=54.792089 tx=120916 date='2010-09-27T08:24:14Z' progress=0.000195 cache=2.0MiB(13411txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000002c486b438b14e6ec59c69fb319a81c5c38e6392135a4dfa3c37002 height=82325 version=0x00000001 log2_work=54.792272 tx=120925 date='2010-09-27T08:40:19Z' progress=0.000195 cache=2.0MiB(13410txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000004e0416d0ff486e710dcddb5072fb797f1e48832aed9cc7af868b8 height=82326 version=0x00000001 log2_work=54.792454 tx=120928 date='2010-09-27T08:45:53Z' progress=0.000195 cache=2.0MiB(13413txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000002be8ed07adbd2a6ddb96bfa73afd75457804ee94785909109eb2ec height=82327 version=0x00000001 log2_work=54.792636 tx=120929 date='2010-09-27T08:46:03Z' progress=0.000195 cache=2.0MiB(13414txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000037e9fc532a9c3557ca64496ab0c5a3726eae298b04c54eae88dd51 height=82328 version=0x00000001 log2_work=54.792819 tx=120931 date='2010-09-27T08:52:03Z' progress=0.000195 cache=2.0MiB(13413txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000003d3bf5bc95774df3cdc19545e0ed5b1e70f6d0baa111353d620466 height=82329 version=0x00000001 log2_work=54.793001 tx=120932 date='2010-09-27T08:52:34Z' progress=0.000195 cache=2.0MiB(13414txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000279a40214b352ede3888c2e42686445e63762967dd91361d1df4aa height=82330 version=0x00000001 log2_work=54.793183 tx=120949 date='2010-09-27T09:14:42Z' progress=0.000195 cache=2.0MiB(13421txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000265c81a54eadcd5c7f5e403e350ea4124bdd16f3cd7452be3c0d79 height=82331 version=0x00000001 log2_work=54.793365 tx=120956 date='2010-09-27T09:20:33Z' progress=0.000195 cache=2.0MiB(13425txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000000cf0653e71280c3c3d913434d27d9c501db51b51b94d17fcb3ef0f height=82332 version=0x00000001 log2_work=54.793547 tx=120959 date='2010-09-27T09:23:22Z' progress=0.000195 cache=2.0MiB(13428txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000356fe81aeddee512cbc03c2fb802c7084c2e5d6254596a3dc6ae3e height=82333 version=0x00000001 log2_work=54.793729 tx=120963 date='2010-09-27T09:26:54Z' progress=0.000195 cache=2.0MiB(13432txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000405ef47c50c2ea882ed36833ee087bad4c17d8d533717dd9bfecce height=82334 version=0x00000001 log2_work=54.793911 tx=120967 date='2010-09-27T09:33:29Z' progress=0.000195 cache=2.0MiB(13436txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000088f0ece302b656ead799ad11e7f8572a16571045e1413a8498975 height=82335 version=0x00000001 log2_work=54.794094 tx=120977 date='2010-09-27T09:37:50Z' progress=0.000195 cache=2.0MiB(13433txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000420f067ef0124f15e80c2f8c6066296fd56bcb918f3e12212ff5c3 height=82336 version=0x00000001 log2_work=54.794276 tx=120985 date='2010-09-27T09:57:24Z' progress=0.000195 cache=2.0MiB(13438txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000029c2898fa25e8f0037c83221a74ecb87200e0e07167a8e3fc16ea height=82337 version=0x00000001 log2_work=54.794458 tx=120987 date='2010-09-27T10:07:14Z' progress=0.000195 cache=2.0MiB(13440txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000241fcc5900aeb88e165ca53b7b90f69eb366967f3cb544fada0196 height=82338 version=0x00000001 log2_work=54.794640 tx=120991 date='2010-09-27T10:10:14Z' progress=0.000195 cache=2.0MiB(13442txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=0000000000384330843e75986af08aec36811e4c9e641466663fcc9a24e96c7b height=82339 version=0x00000001 log2_work=54.794822 tx=120997 date='2010-09-27T10:29:05Z' progress=0.000195 cache=2.0MiB(13441txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=000000000005bb365e4a60b70c305665cb5c1cfb1e9f2c6e9111fbdecd2c01c9 height=82340 version=0x00000001 log2_work=54.795004 tx=120998 date='2010-09-27T10:30:31Z' progress=0.000195 cache=2.0MiB(13442txo)
bitcoin              | 2021-02-28T16:03:05Z UpdateTip: new best=00000000003b0c76cf4fb782ebb8038b337c25474be794b917ac804c65a10c1c height=82341 version=0x00000001 log2_work=54.795186 tx=121001 date='2010-09-27T10:39:09Z' progress=0.000195 cache=2.0MiB(13444txo)

LND logs
--------

Attaching to lnd
lnd                  | 2021-02-28 16:02:23.456 [WRN] BTCN: Banning peer 139.162.190.98:8333: duration=48h0m0s, reason=peer was unable to serve compact filters
lnd                  | 2021-02-28 16:02:23.517 [INF] BTCN: Lost peer 139.162.190.98:8333 (outbound)
lnd                  | 2021-02-28 16:02:24.675 [WRN] BTCN: Banning peer 128.199.6.24:8333: duration=48h0m0s, reason=peer was unable to serve compact filters
lnd                  | 2021-02-28 16:02:24.725 [INF] BTCN: Lost peer 128.199.6.24:8333 (outbound)
lnd                  | 2021-02-28 16:02:26.621 [WRN] BTCN: Banning peer 34.220.232.238:8333: duration=48h0m0s, reason=peer was unable to serve compact filters
lnd                  | 2021-02-28 16:02:26.675 [INF] BTCN: Lost peer 34.220.232.238:8333 (outbound)
lnd                  | 2021-02-28 16:02:31.052 [WRN] BTCN: Banning peer 34.86.228.49:8333: duration=48h0m0s, reason=peer was unable to serve compact filters
lnd                  | 2021-02-28 16:02:31.108 [INF] BTCN: Lost peer 34.86.228.49:8333 (outbound)
lnd                  | 2021-02-28 16:02:32.519 [INF] BTCN: Processed 6000 blocks in the last 1m19.77s (height 27112, 2009-11-15 03:19:00 +0000 UTC)
lnd                  | 2021-02-28 16:02:32.675 [INF] BTCN: Starting cfheaders sync from (block_height=27000, block_hash=000000002cc4a38b7e2e9d45b0fe677806d841835af340b10e5c8b51811e6572) to (block_height=29111, block_hash=000000007543d8ed50eee5f5a377d14065b6e8e4b59d699f453c9c08e6aab4e9)
lnd                  | 2021-02-28 16:02:32.675 [INF] BTCN: Starting cfheaders sync for filter_type=0
lnd                  | 2021-02-28 16:02:32.676 [INF] BTCN: Fetching set of checkpointed cfheaders filters from height=27000, hash=1646b766e4c24d409e9a1455a0c79eeb7d82041593518a75a480645dabfc2a96
lnd                  | 2021-02-28 16:02:32.676 [INF] BTCN: Starting to query for cfheaders from checkpoint_interval=27, checkpoints=29
lnd                  | 2021-02-28 16:02:32.676 [INF] BTCN: Attempting to query for 1 cfheader batches
lnd                  | 2021-02-28 16:02:34.508 [INF] BTCN: Verified 4000 filter headers in the last 1m5.74s (height 27001, 2009-11-13 19:32:53 +0000 UTC)
lnd                  | 2021-02-28 16:02:34.514 [INF] BTCN: Successfully got filter headers for 29 checkpoints
lnd                  | 2021-02-28 16:02:34.514 [INF] BTCN: Waiting for more block headers, then will start cfheaders sync from height 29000...
lnd                  | 2021-02-28 16:02:42.525 [INF] BTCN: Processed 2000 blocks in the last 10s (height 29112, 2009-12-08 22:55:19 +0000 UTC)
lnd                  | 2021-02-28 16:02:42.675 [INF] BTCN: Starting cfheaders sync from (block_height=29000, block_hash=00000000b8b9f3b66b43b045aedc3380780df7e492866683c59efa770bb9a3a9) to (block_height=31111, block_hash=000000001000315e95d60da89da610b116f385acda9df5659eeb5aab8881630e)
lnd                  | 2021-02-28 16:02:42.675 [INF] BTCN: Starting cfheaders sync for filter_type=0
lnd                  | 2021-02-28 16:02:42.675 [INF] BTCN: Fetching set of checkpointed cfheaders filters from height=29000, hash=e559e7dddb592b32e028b2e5614bc819aca27647d4dfa4c2297009e29b1d3acb
lnd                  | 2021-02-28 16:02:42.675 [INF] BTCN: Starting to query for cfheaders from checkpoint_interval=29, checkpoints=31
lnd                  | 2021-02-28 16:02:42.675 [INF] BTCN: Attempting to query for 1 cfheader batches
lnd                  | 2021-02-28 16:02:42.934 [WRN] BTCN: Banning peer 35.200.167.38:8333: duration=48h0m0s, reason=peer was unable to serve compact filters
lnd                  | 2021-02-28 16:02:42.991 [INF] BTCN: Lost peer 35.200.167.38:8333 (outbound)
lnd                  | 2021-02-28 16:02:44.675 [WRN] BTCN: Query(7) from peer 188.127.188.23:8333 failed, rescheduling: did not get response before timeout
lnd                  | 2021-02-28 16:02:44.841 [INF] BTCN: Verified 2000 filter headers in the last 10.33s (height 29001, 2009-12-07 22:22:19 +0000 UTC)
lnd                  | 2021-02-28 16:02:44.847 [INF] BTCN: Successfully got filter headers for 31 checkpoints
lnd                  | 2021-02-28 16:02:44.847 [INF] BTCN: Waiting for more block headers, then will start cfheaders sync from height 31000...
lnd                  | 2021-02-28 16:02:51.391 [INF] BTCN: New valid peer 34.73.79.114:8333 (outbound) (/btcwire:0.5.0/btcd:0.20.0/)

Tor logs
--------

Attaching to tor
tor                  | Feb 28 16:00:53.000 [notice] Bootstrapped 63% (loading_descriptors): Loading relay descriptors
tor                  | Feb 28 16:00:53.000 [notice] Bootstrapped 68% (loading_descriptors): Loading relay descriptors
tor                  | Feb 28 16:00:53.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
tor                  | Feb 28 16:00:53.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
tor                  | Feb 28 16:00:53.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
tor                  | Feb 28 16:00:54.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
tor                  | Feb 28 16:00:54.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tor                  | Feb 28 16:00:55.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tor                  | Feb 28 16:00:55.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor                  | Feb 28 16:00:56.000 [notice] Bootstrapped 100% (done): Done
tor                  | Feb 28 16:00:59.000 [warn] Guard helena ($5CFC486780CBD4446B764E51608D6574003B350D) is failing an extremely large amount of circuits. This could indicate a route manipulation attack, extreme network overload, or a bug. Success counts are 4/151. Use counts are 3/3. 4 circuits completed, 0 were unusable, 0 collapsed, and 0 timed out. For reference, your timeout cutoff is 60 seconds.
tor                  | Feb 28 16:00:59.000 [notice] Guard helena ($5CFC486780CBD4446B764E51608D6574003B350D) is failing more circuits than usual. Most likely this means the Tor network is overloaded. Success counts are 95/165. Use counts are 74/74. 95 circuits completed, 0 were unusable, 0 collapsed, and 0 timed out. For reference, your timeout cutoff is 60 seconds.
tor                  | Feb 28 16:00:59.000 [notice] Your network connection speed appears to have changed. Resetting timeout to 60s after 18 timeouts and 117 buildtimes.
tor                  | Feb 28 16:01:08.000 [notice] Your network connection speed appears to have changed. Resetting timeout to 60s after 18 timeouts and 137 buildtimes.
tor                  | Feb 28 16:01:34.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $6A389E641551EC5C84F927713F08F1607AF742B7~Unnamed at 91.192.103.16. Retrying on a new circuit.
tor                  | Feb 28 16:01:49.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
tor                  | Feb 28 16:01:50.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $8839E8FBE28219B85392EEA5A4DBC41D315F4B83~relayon0206 at 185.220.101.139. Retrying on a new circuit.
tor                  | Feb 28 16:01:57.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
tor                  | Feb 28 16:02:05.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $34E127C099E3F2D28F8223EDDE1CA6E511338A20~neko at 185.130.44.124. Retrying on a new circuit.
tor                  | Feb 28 16:02:20.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $1503B630DCFC424F039B2C0AB5B6DF24D86F7F79~node27 at 185.10.68.92. Retrying on a new circuit.
tor                  | Feb 28 16:02:24.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
tor                  | Feb 28 16:02:34.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
tor                  | Feb 28 16:02:35.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $3D24010B53A4ED6170D387F78B932CAF73527008~AZ at 91.192.103.25. Retrying on a new circuit.
tor                  | Feb 28 16:02:41.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
tor                  | Feb 28 16:02:45.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $74A19D86DDF63F1133B414B81F36E1F44640811F~Unnamed at 62.210.105.116. Retrying on a new circuit.
tor                  | Feb 28 16:02:50.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $59A5BACFE32B6CA0F8F67B6621B3E8B89312CB7A~Quetzalcoatl at 104.244.79.196. Retrying on a new circuit.
tor                  | Feb 28 16:02:50.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:8333. Giving up.
tor                  | Feb 28 16:03:00.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $6FBD65C22C2996B2038A090BF5E55AA7AEDEE120~relayon0351 at 185.220.101.218. Retrying on a new circuit.
tor                  | Feb 28 16:03:01.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $6FBD65C22C2996B2038A090BF5E55AA7AEDEE120~relayon0351 at 185.220.101.218. Retrying on a new circuit.
tor                  | Feb 28 16:03:03.000 [notice] We tried for 15 seconds to connect to '[scrubbed]' using exit $6FBD65C22C2996B2038A090BF5E55AA7AEDEE120~relayon0351 at 185.220.101.218. Retrying on a new circuit.
================
==== Result ====
================
This script could not automatically detect an issue with your Umbrel.
Please share the following links and paste it in the Umbrel Telegram group (https://t.me/getumbrel) so we can help you with your problem.
https://umbrel-paste.vercel.app/wt001nu
```

------ 4) Now I go to the folder "/ usr / local / bin /" and it's still empty. She has nothing inside like before. 



Well people, I don't know what else to do. For now everything works, but when it reaches 100% synchronization that is where I can no longer access Umbrel through the web page (http://192.168.100.30/).

Greetings!!! and then I tell them what happened.

**Comment by louneskmt** [comment]
Your first issue (with SQLite) has been solved here: https://github.com/getumbrel/umbrel/pull/591. A fix has been released as this issue affected all the new people to Umbrel, or doing an update. 

It is normal that the SSH commands don't work for you, are these allow you to connect to your Pi. If you don't run Umbrel on a Raspberry Pi, they won't work. SSH allow to open a remote terminal, which you don't need if you have already access to the terminal of the computer where Umbrel is installed. 

All seems good to me in your latest debug result. Do you still face any issue?

**Comment by Prideone** [comment]
Hi @louneskmt !!! thanks for your help.
> Your first issue (with SQLite) has been solved here: #591. A fix has been released as this issue affected all the new people to Umbrel, or doing an update.

It is the content of the "docker-compose.yml" file. I have it the same now (previously I have no idea). Like I already made a copy in case the synchronization reaches 100% and I have the same problem, I try checking if that file was modified something. 

> It is normal that the SSH commands don't work for you, are these allow you to connect to your Pi. If you don't run Umbrel on a Raspberry Pi, they won't work. SSH allow to open a remote terminal, which you don't need if you have already access to the terminal of the computer where Umbrel is installed.

I am trying to run my node on Linux openSUSE 15.2, not on Raspberry Pi. Something works because I can access Umbrel in the meantime (when it reaches 100% is where it gives me the error and I cannot connect). 

> All seems good to me in your latest debug result. Do you still face any issue?

No, it works fine while updating (like the last two times). I suppose that when it reaches 100% synchronization of the blocks, there must be a problem when it starts to load the "Mempool" (which was never added at all times, since it is 0 Bytes). I think that after synchronizing, I have to start loading the mempool and there is the problem. (I'm very noob) 

In two days it will be 100% and there I will see if I get the same error. I will check the file "docker-compose.yml".

Another thing I deduced ... is about the bitcoin error when it did not start me previously:
```
Attaching to bitcoin
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_libversion: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_prepare_v2: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_bind_blob: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_open: symbol not found
bitcoin | Error loading shared library libsqlite3.so.0: No such file or directory (needed by / usr / local / bin / bitcoind)
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_column_text: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_close: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_column_int: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_reset: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_clear_bindings: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_open_v2: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_column_bytes: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_shutdown: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_exec: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_config: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_backup_step: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_db_readonly: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_backup_init: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_finalize: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_get_autocommit: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_step: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_backup_finish: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_errstr: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_errmsg: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_column_blob: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_initialize: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_libversion: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_prepare_v2: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_bind_blob: symbol not found
bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_open: symbol not found 
```
And it is that if I am mounting this partition (synchronization less than 100%):
`/ var / lib / docker / overlay2 / 93188548d0dd1af49e4eb1aa76a9ba30b90512a60a48974a29e411c15bf8a1d2 / merged / usr / local / bin /`
So when it said in the above error on each line, for example, "bitcoin | Error relocating / usr / local / bin / bitcoind: sqlite3_open: symbol not found", it was about the folder "/ var / lib / docker / overlay2. ... ".
I don't know why this docker "image / container" was not mounted earlier. Because every time I rebooted the container it appeared and disappeared and restarted every minute.

Let's wait and see what happens. Thanks a lot!!!!

**Comment by Prideone** [comment]
Good news people !! Finally solved !!!

The "Bitcoind" docker no longer restarts itself and works perfectly. So that problem is solved (here: #591.).

Thanks!!! ^. ^

**Comment by nmfretz** [comment]
closing old support issue
